CREATE TABLE area (
    id INT PRIMARY KEY AUTO_INCREMENT,
    colony_name VARCHAR(255) NOT NULL,
    landmark VARCHAR(255),
    pincode VARCHAR(10) NOT NULL,
    city_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);