CREATE TABLE IF NOT EXISTS `users` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`username` varchar(255) NOT NULL UNIQUE,
`password` varchar(255) NOT NULL,
`first_name` varchar(100) NULL,
`middle_name` varchar(100) NULL,
`last_name` varchar(100) NULL,
`first_name_hindi` varchar(100) NULL,
`middle_name_hindi` varchar(100) NULL,
`last_name_hindi` varchar(100) NULL,
`user_type` SMALLINT(10) NULL,
`address` TEXT NULL,
`city` varchar(10),
`postal_code` varchar(10),
`last_login` datetime NOT NULL,
`login_count` int(11) DEFAULT 0,
`is_active` boolean DEFAULT 0,
`created_by` int(10) NOT NULL,
`updated_by` int(10),
`total_purchase` bigint,
`area` int(11) DEFAULT null,
`total_sales`bigint,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
